### ISSUE TITLE
Draft proposal for tracking MONDO changes

### ISSUE THREAD

**Issue by dazzariti** [clingen-data-model/data-exchange-topics#7] opened 2021-09-07 13:16 UTC
Related to CSP-194

Larry will prepare a proposal for accessing the MONDO data and sending alerts through the Data Exchange about updates and changes

- Proposal will include the types of notifications that could come through (this is required to give the curation systems and curators the information they need to know to come up with a plan for how to respond)
- Sept 17th Infrastructure call (Friday at 1pm ET) - Larry to present proposal and message types, bring together representatives from each team listed above
- Hannah will coordinate this call and make sure everyone involved is included, Nicole V optional

From DPWG Co-chair call notes:

Larry will be putting together a proposal to assess the source of MONDO data (with Nicole) and to be sure that it provides ClinGen enough consistency and structure that we can develop a simplified solution to notifying consumers of a data exchange topic. 

This proposal message format/content and scope will be shared with everyone before any implementation begins (expectation is that Kyle Ferriter will be able to stand it up pretty quickly - end of Oct at latest).

discussion on providing a clingen wide policy for keeping all tools that use mondo in sync with versions and updates is out of scope for now, but we can continue to discuss.

Handling of changes from notifications will be the responsibility of the curation apps and gene tracker to sort out a plan as we begin to better understand the various use cases for re-curation vs re-labeling.

**Comment by larrybabb** [comment] 2021-09-14 14:53
duplicate of #8

**Closed by larrybabb** 2021-09-14 14:53 UTC
